name: Boosting Training Brick v1.0
description: Training brick for kumar2004/ml-base:v1
inputs:
  - {name: train_X, type: Dataset, description: "Final training features"}
  - {name: train_y, type: Dataset, description: "Training target labels"}
  - {name: untrained_model, type: Model, description: "Untrained model object"}
  - {name: model_metadata, type: Data, description: "Model metadata"}
  - {name: preprocess_metadata, type: Data, description: "Preprocessing metadata"}
  - {name: pca_metadata, type: Data, description: "PCA metadata", optional: true}
  - {name: enable_pca, type: String, description: "Whether PCA was enabled", optional: true, default: "false"}
  - {name: model_type, type: String, description: "classification or regression", optional: true, default: "classification"}
  - {name: early_stopping_rounds, type: Integer, description: "Early stopping rounds", optional: true, default: "10"}
  - {name: validation_split, type: Float, description: "Validation split ratio", optional: true, default: "0.1"}
  - {name: random_state, type: Integer, description: "Random seed", optional: true, default: "42"}
  - {name: n_jobs, type: Integer, description: "Number of CPU cores", optional: true, default: "-1"}
  - {name: device, type: String, description: "cpu, cuda, or auto", optional: true, default: "auto"}
outputs:
  - {name: trained_model, type: Model, description: "Trained model object"}
  - {name: training_metadata, type: Data, description: "Training metadata JSON"}
  - {name: validation_metrics, type: Data, description: "Validation metrics JSON"}
  - {name: feature_importance, type: Data, description: "Feature importance JSON"}

implementation:
  container:
    image: kumar2004/ml-base:v1
    command:
      - python3
      - -u
      - -c
      - |
        import argparse, os, sys, json, traceback, warnings, importlib.util
        from datetime import datetime
        import numpy as np
        import pandas as pd
        from sklearn.model_selection import train_test_split
        from sklearn.metrics import (
            accuracy_score, precision_score, recall_score, f1_score,
            roc_auc_score, log_loss, mean_squared_error, mean_absolute_error, r2_score
        )
        import joblib
        
        print("="*80)
        print("TRAINING BRICK - LIBRARY CHECK")
        print("="*80)
        
        # Function to check if library is available
        def is_library_available(library_name):
            try:
                spec = importlib.util.find_spec(library_name)
                return spec is not None
            except Exception:
                return False
        
        # Check what's available
        boosting_libs = ['xgboost', 'lightgbm', 'catboost']
        available_libs = {}
        
        for lib in boosting_libs:
            if is_library_available(lib):
                available_libs[lib] = True
                print(f"✓ {lib} available")
            else:
                available_libs[lib] = False
                print(f"✗ {lib} not available")
        
        # Import what's available
        XGB_AVAILABLE = available_libs.get('xgboost', False)
        LGB_AVAILABLE = available_libs.get('lightgbm', False)
        CB_AVAILABLE = available_libs.get('catboost', False)
        
        if XGB_AVAILABLE:
            try:
                import xgboost as xgb
                print(f"✓ XGBoost {xgb.__version__} loaded")
            except Exception:
                XGB_AVAILABLE = False
                print("⚠ XGBoost import failed")
        
        if LGB_AVAILABLE:
            try:
                import lightgbm as lgb
                print(f"✓ LightGBM {lgb.__version__} loaded")
            except Exception:
                LGB_AVAILABLE = False
                print("⚠ LightGBM import failed")
        
        if CB_AVAILABLE:
            try:
                import catboost as cb
                print(f"✓ CatBoost {cb.__version__} loaded")
            except Exception:
                CB_AVAILABLE = False
                print("⚠ CatBoost import failed")
        
        print("="*80)
        
        # Suppress warnings
        warnings.filterwarnings('ignore')
        
        # ============================================================================
        # TRAINING FUNCTION
        # ============================================================================
        def train_model_safely(model, X_train, y_train, X_val=None, y_val=None):
            model_class_name = model.__class__.__name__.lower()
            
            # XGBoost training
            if XGB_AVAILABLE and 'xgboost' in model_class_name:
                try:
                    fit_params = {}
                    if X_val is not None and y_val is not None and len(X_val) > 0:
                        fit_params['eval_set'] = [(X_val, y_val)]
                        fit_params['verbose'] = False
                    return model.fit(X_train, y_train, **fit_params)
                except Exception as e:
                    print(f"[WARNING] XGBoost fit with validation failed: {str(e)[:100]}")
                    return model.fit(X_train, y_train)
            
            # LightGBM training
            elif LGB_AVAILABLE and 'lgbm' in model_class_name:
                try:
                    fit_params = {}
                    if X_val is not None and y_val is not None and len(X_val) > 0:
                        fit_params['eval_set'] = [(X_val, y_val)]
                        fit_params['verbose'] = False
                    return model.fit(X_train, y_train, **fit_params)
                except Exception as e:
                    print(f"[WARNING] LightGBM fit with validation failed: {str(e)[:100]}")
                    return model.fit(X_train, y_train)
            
            # CatBoost training
            elif CB_AVAILABLE and 'catboost' in model_class_name:
                try:
                    fit_params = {}
                    if X_val is not None and y_val is not None and len(X_val) > 0:
                        fit_params['eval_set'] = [(X_val, y_val)]
                        fit_params['verbose'] = False
                    return model.fit(X_train, y_train, **fit_params)
                except Exception as e:
                    print(f"[WARNING] CatBoost fit with validation failed: {str(e)[:100]}")
                    return model.fit(X_train, y_train)
            
            # Sklearn models
            else:
                return model.fit(X_train, y_train)
        
        # ============================================================================
        # METRICS FUNCTION
        # ============================================================================
        def calculate_model_metrics(model, X, y_true, task_type):
            metrics = {}
            try:
                y_pred = model.predict(X)
                
                if task_type == 'classification':
                    metrics['accuracy'] = float(accuracy_score(y_true, y_pred))
                    metrics['precision'] = float(precision_score(y_true, y_pred, average='weighted', zero_division=0))
                    metrics['recall'] = float(recall_score(y_true, y_pred, average='weighted', zero_division=0))
                    metrics['f1_score'] = float(f1_score(y_true, y_pred, average='weighted', zero_division=0))
                    
                    # Try ROC AUC
                    try:
                        if hasattr(model, 'predict_proba'):
                            y_proba = model.predict_proba(X)
                            if len(np.unique(y_true)) > 1:
                                if y_proba.shape[1] == 2:
                                    metrics['roc_auc'] = float(roc_auc_score(y_true, y_proba[:, 1]))
                                else:
                                    metrics['roc_auc'] = float(roc_auc_score(y_true, y_proba, multi_class='ovr'))
                    except:
                        metrics['roc_auc'] = None
                
                else:  # regression
                    metrics['mse'] = float(mean_squared_error(y_true, y_pred))
                    metrics['rmse'] = float(np.sqrt(metrics['mse']))
                    metrics['mae'] = float(mean_absolute_error(y_true, y_pred))
                    metrics['r2'] = float(r2_score(y_true, y_pred))
            
            except Exception as e:
                print(f"[METRICS WARNING] {str(e)[:80]}")
            
            return metrics
        
        # ============================================================================
        # MAIN FUNCTION
        # ============================================================================
        def main():
            parser = argparse.ArgumentParser()
            parser.add_argument('--train_X', type=str, required=True)
            parser.add_argument('--train_y', type=str, required=True)
            parser.add_argument('--untrained_model', type=str, required=True)
            parser.add_argument('--model_metadata', type=str, required=True)
            parser.add_argument('--preprocess_metadata', type=str, required=True)
            parser.add_argument('--pca_metadata', type=str, required=False, default="")
            parser.add_argument('--enable_pca', type=str, default='false')
            parser.add_argument('--model_type', type=str, default='classification')
            parser.add_argument('--early_stopping_rounds', type=int, default=10)
            parser.add_argument('--validation_split', type=float, default=0.1)
            parser.add_argument('--random_state', type=int, default=42)
            parser.add_argument('--n_jobs', type=int, default=-1)
            parser.add_argument('--device', type=str, default='auto')
            parser.add_argument('--trained_model', type=str, required=True)
            parser.add_argument('--training_metadata', type=str, required=True)
            parser.add_argument('--validation_metrics', type=str, required=True)
            parser.add_argument('--feature_importance', type=str, required=True)
            args = parser.parse_args()
            
            try:
                print("[STEP 1] Loading data...")
                X_train = pd.read_parquet(args.train_X)
                y_train = pd.read_parquet(args.train_y)
                print(f"  X shape: {X_train.shape}")
                print(f"  y shape: {y_train.shape}")
                
                # Handle single vs multi-target
                if isinstance(y_train, pd.DataFrame):
                    y_train_single = y_train.iloc[:, 0]
                    print(f"  Using first column of {y_train.shape[1]} targets")
                else:
                    y_train_single = y_train
                
                print("[STEP 2] Loading model...")
                model = joblib.load(args.untrained_model)
                print(f"  Model type: {model.__class__.__name__}")
                
                print("[STEP 3] Creating validation split...")
                task = args.model_type.strip().lower()
                
                if args.validation_split > 0 and X_train.shape[0] > 10:
                    if task == 'classification' and len(np.unique(y_train_single)) > 1:
                        X_train_split, X_val, y_train_split, y_val = train_test_split(
                            X_train, y_train_single,
                            test_size=args.validation_split,
                            stratify=y_train_single,
                            random_state=args.random_state
                        )
                    else:
                        X_train_split, X_val, y_train_split, y_val = train_test_split(
                            X_train, y_train_single,
                            test_size=args.validation_split,
                            random_state=args.random_state
                        )
                    print(f"  Training: {X_train_split.shape[0]} samples")
                    print(f"  Validation: {X_val.shape[0]} samples")
                else:
                    X_train_split, y_train_split = X_train, y_train_single
                    X_val, y_val = None, None
                    print("  Using all data for training")
                
                print("[STEP 4] Training model...")
                trained_model = train_model_safely(model, X_train_split, y_train_split, X_val, y_val)
                print("  Training completed")
                
                print("[STEP 5] Calculating metrics...")
                train_metrics = calculate_model_metrics(trained_model, X_train_split, y_train_split, task)
                val_metrics = {}
                if X_val is not None and y_val is not None:
                    val_metrics = calculate_model_metrics(trained_model, X_val, y_val, task)
                
                print("[STEP 6] Saving outputs...")
                # Create directories
                os.makedirs(os.path.dirname(args.trained_model) or ".", exist_ok=True)
                os.makedirs(os.path.dirname(args.training_metadata) or ".", exist_ok=True)
                os.makedirs(os.path.dirname(args.validation_metrics) or ".", exist_ok=True)
                os.makedirs(os.path.dirname(args.feature_importance) or ".", exist_ok=True)
                
                # Save trained model
                joblib.dump(trained_model, args.trained_model)
                
                # Training metadata
                training_metadata = {
                    'timestamp': datetime.utcnow().isoformat() + 'Z',
                    'model_class': trained_model.__class__.__name__,
                    'data_info': {
                        'training_samples': int(X_train.shape[0]),
                        'features': int(X_train.shape[1]),
                        'validation_samples': int(X_val.shape[0]) if X_val is not None else 0
                    },
                    'available_libraries': {
                        'xgboost': XGB_AVAILABLE,
                        'lightgbm': LGB_AVAILABLE,
                        'catboost': CB_AVAILABLE
                    }
                }
                
                # Validation metrics
                validation_metrics_data = {
                    'training_metrics': train_metrics,
                    'validation_metrics': val_metrics,
                    'timestamp': datetime.utcnow().isoformat() + 'Z'
                }
                
                # Feature importance (simplified)
                feature_importance_data = {
                    'feature_names': list(X_train.columns),
                    'algorithm': trained_model.__class__.__name__,
                    'note': 'Feature importance extraction depends on model type'
                }
                
                # Save JSON files
                with open(args.training_metadata, 'w') as f:
                    json.dump(training_metadata, f, indent=2)
                
                with open(args.validation_metrics, 'w') as f:
                    json.dump(validation_metrics_data, f, indent=2)
                
                with open(args.feature_importance, 'w') as f:
                    json.dump(feature_importance_data, f, indent=2)
                
                print("\\n" + "="*80)
                print("TRAINING COMPLETE")
                print("="*80)
                print(f"Model: {trained_model.__class__.__name__}")
                print(f"Samples: {X_train.shape[0]}")
                print(f"Features: {X_train.shape[1]}")
                
                if task == 'classification':
                    if train_metrics.get('accuracy'):
                        print(f"Training Accuracy: {train_metrics['accuracy']:.4f}")
                    if val_metrics.get('accuracy'):
                        print(f"Validation Accuracy: {val_metrics['accuracy']:.4f}")
                else:
                    if train_metrics.get('r2'):
                        print(f"Training R²: {train_metrics['r2']:.4f}")
                    if val_metrics.get('r2'):
                        print(f"Validation R²: {val_metrics['r2']:.4f}")
                
                print(f"\\nOutputs saved:")
                print(f"  ✓ trained_model: {args.trained_model}")
                print(f"  ✓ training_metadata: {args.training_metadata}")
                print(f"  ✓ validation_metrics: {args.validation_metrics}")
                print(f"  ✓ feature_importance: {args.feature_importance}")
                print("="*80)
                
            except Exception as e:
                print(f"\\nERROR: {e}")
                traceback.print_exc()
                sys.exit(1)
        
        if __name__ == "__main__":
            main()
    args:
      - --train_X
      - {inputPath: train_X}
      - --train_y
      - {inputPath: train_y}
      - --untrained_model
      - {inputPath: untrained_model}
      - --model_metadata
      - {inputPath: model_metadata}
      - --preprocess_metadata
      - {inputPath: preprocess_metadata}
      - --pca_metadata
      - {inputPath: pca_metadata}
      - --enable_pca
      - {inputValue: enable_pca}
      - --model_type
      - {inputValue: model_type}
      - --early_stopping_rounds
      - {inputValue: early_stopping_rounds}
      - --validation_split
      - {inputValue: validation_split}
      - --random_state
      - {inputValue: random_state}
      - --n_jobs
      - {inputValue: n_jobs}
      - --device
      - {inputValue: device}
      - --trained_model
      - {outputPath: trained_model}
      - --training_metadata
      - {outputPath: training_metadata}
      - --validation_metrics
      - {outputPath: validation_metrics}
      - --feature_importance
      - {outputPath: feature_importance}
